# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-02 23:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.UUIDField(null=True)),
                ('currency', models.CharField(choices=[('RUB', 'RUB'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('CHF', 'CHF'), ('USD', 'USD')], max_length=3, verbose_name='currency')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total amount')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('w', 'withdrawal'), ('d', 'deposit')], max_length=1, verbose_name='Transaction type')),
                ('when', models.DateTimeField(verbose_name='Time')),
                ('total', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Summ')),
                ('comment', models.CharField(max_length=255, verbose_name='Comment')),
                ('state', models.BooleanField()),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='income_transfers', to='app.Account', verbose_name='DestinationAccount')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outcome_transfers', to='app.Account', verbose_name='SourceAccount')),
            ],
        ),
    ]
